# Generated by Django 4.2.30 on 2026-04-18 10:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('available_stocks', models.PositiveIntegerField(default=0)),
                ('unit_price', models.FloatField()),
                ('tax_percentage', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_price_without_tax', models.FloatField(default=0.0)),
                ('total_tax_payable', models.FloatField(default=0.0)),
                ('net_price', models.FloatField(default=0.0)),
                ('rounded_net_price', models.FloatField(default=0.0)),
                ('cash_paid', models.FloatField(default=0.0)),
                ('balance_payable', models.FloatField(default=0.0)),
                ('denomination_input', models.JSONField(default=dict)),
                ('balance_denomination', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price_at_purchase', models.FloatField()),
                ('tax_percentage_at_purchase', models.FloatField()),
                ('purchase_price', models.FloatField()),
                ('tax_payable', models.FloatField()),
                ('total_price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.purchase')),
            ],
        ),
    ]
